### PR TITLE
Add SignalBoost entry

### PR DESCRIPTION
**Pull request by ansimita**
I hope that it's okay for me to replace John Doe. If not, let me know and I'll perform an addition instead.

### CODE REVIEW

**Comment by Quinncuatro** [comment]
No, this looks good to me!

Though, I'm seeing "Nate" on your Twitter. Is "Natthan" correct in the YAML file?

**Comment by ansimita** [comment]
> Nate is a given name, frequently used as a diminutive of Nathan or Nathaniel. — [Wikipedia](https://en.wikipedia.org/wiki/Nate_(name))

"Natthan" in the YAML file is correct. 🙂

**Comment by Quinncuatro** [comment]
Word! Just have never seen it with two T's before. Wanted to make sure it wasn't a typo.

**Review by Quinncuatro — APPROVED** [review]

**Comment by Quinncuatro** [comment]
Just a heads up - I added more options for outbound links in the signal boost blocks:

https://github.com/Quinncuatro/Henry-Personal-Website/blob/master/src/signalboost/README.md

**Pull request merged**
